---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tasks-high
spec:
  hard:
    cpu: "32"
    memory: 64Gi
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["airflow-tasks"]
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: airflow-tasks
value: 1000000
globalDefault: false
description: "This class should be used for Airflow task pods only."