---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}
type: Opaque
stringData:
  AIRFLOW__CORE__REMOTE_LOGGING: "True"
  AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://example-airflow-logs/airflowcore/logs"
  AIRFLOW__TAILS__STAGE: {{ .Values.stage }}
  SENTRY_ENVIRONMENT: {{ .Values.stage }}
  GE_SNOWFLAKE_USERNAME: {{ .Values.GE_SNOWFLAKE_USERNAME }}
  GE_SNOWFLAKE_PASSWORD: {{ .Values.GE_SNOWFLAKE_PASSWORD }}
  GE_SNOWFLAKE_HOST: {{ .Values.GE_SNOWFLAKE_HOST }}
  GE_SNOWFLAKE_DATABASE: {{ .Values.GE_SNOWFLAKE_DATABASE }}
  GE_SNOWFLAKE_SCHEMA: {{ .Values.GE_SNOWFLAKE_SCHEMA }}
  GITHUB_API_KEY: {{ .Values.GITHUB_API_KEY }}
  EMARSYS_API_USERNAME: {{ .Values.EMARSYS_API_USERNAME }}
  EMARSYS_API_SECRET: {{ .Values.EMARSYS_API_SECRET }}
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: {{ .Values.AIRFLOW__CORE__SQL_ALCHEMY_CONN }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: 123456.dkr.ecr.eu-west-1.amazonaws.com/tails/data/{{ .Values.app_name }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ .Values.commitid }}
  AIRFLOW__KUBERNETES__NAMESPACE: {{ .Values.app_name }}
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: "/home/airflowuser/airflow/airflow_pod_template.yml"